[theme]
# Warna utama untuk tombol, slider, dan elemen aktif
primaryColor = "001845"

# Warna background halaman utama
backgroundColor = "#B8CFFF"

# Warna background sidebar dan kotak input
secondaryBackgroundColor = "D1E1FF"

# Warna teks utama
textColor = "000000"

# Pilihan font: "sans serif", "serif", atau "monospace"
font = "sans serif"
