[theme]
# Warna utama untuk tombol, slider, dan elemen aktif
primaryColor = "2E74FF"

# Warna background halaman utama
backgroundColor = "#0055FF"

# Warna background sidebar dan kotak input
secondaryBackgroundColor = "#FFF14D"

# Warna teks utama
textColor = "000000"

# Pilihan font: "sans serif", "serif", atau "monospace"
font = "sans serif"
